server:
  port: 0

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          inventory-service:
            loggerLevel: basic
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: "12345"
  sql:
    init:
      mode: always

logging:
  level:
    ru.yandex.practicum.order.feign.InventoryClient: DEBUG
