server:
  port: 0

spring:
  cloud:
    openfeign:
      circuitbreaker:
        # Создаёт Circuit Breaker для удалённых вызовов через Feign.
        enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000
          inventory-service:
            loggerLevel: basic
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: dbuser
    password: "12345"
  sql:
    init:
      mode: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        # Количество последних вызовов, учитываемых при оценке сбоев.
        sliding-window-size: 5
        # Доля ошибок в процентах, после которой Circuit Breaker размыкается.
        failure-rate-threshold: 50
        # Сколько Circuit Breaker остаётся разомкнутым перед проверкой восстановления.
        wait-duration-in-open-state: 10s
        # Число пробных вызовов в полуоткрытом состоянии для проверки сервиса.
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    configs:
      default:
        # Максимальное время ожидания удалённого вызова до тайм-аута.
        timeout-duration: 3s
logging:
  level:
    ru.yandex.practicum.order.feign.InventoryClient: DEBUG
