server:
  port: 0

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: dbuser
    password: "12345"
  sql:
    init:
      mode: always
